# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AHS CAP ONLINE
description: >- # this means to ignore newlines until "baseurl:"
  AHS Capstone provides Olin students the opportunity to dive deep in their AHS concentration and create an original, independent project with guidance and input from content-expert mentors. Each year, the AHS Capstone class has a tradition of sharing our work with the Olin community in a live, interactive exhibit—inspiring current conversations and future AHS work and play. During this time of social distancing, we believe AHS can uplift, inspire, and connect us more than ever—so we offer to you “AHS Cap at a Distance”.
baseurl: "/ahs-capstone-exhibit" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  projects:
    output: true
    permalink: /projects/:title/


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
